export const data = [
  {
    id: '8943',
    title: 'Espaguete Coco Bambu (2 pessoas)',
    description:
      '220g de cebolas com espaguete italiano, ervilhas, presunto e molho branco. Gratinado com farta camada de queijos muçarela e parmesão.',
    price: 100,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-01',
    updated_at: '2022-01-01',
    category: ['Espaguete', 'Lançamentos'],
  },
  {
    id: '8944',
    title: 'Filé à Parmegiana (2 pessoas)',
    description:
      'Filé à parmegiana com molho de tomate, queijo muçarela e parmesão, acompanhado de arroz branco e batata frita.',
    price: 120,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-02',
    updated_at: '2022-01-02',
    category: ['Filé', 'Lançamentos'],
  },
  // Adicionando mais 28 pratos de comida
  {
    id: '8945',
    title: 'Frango à Passarinho',
    description:
      'Pedacinhos de frango fritos e temperados com alho, servidos com limão e pimenta.',
    price: 80,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-03',
    updated_at: '2022-01-03',
    category: ['Frango', 'Petiscos'],
  },
  {
    id: '8946',
    title: 'Risoto de Funghi',
    description:
      'Risoto cremoso preparado com cogumelos funghi porcini, caldo de legumes, arroz arbóreo, cebola, alho, vinho branco e queijo parmesão.',
    price: 90,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-04',
    updated_at: '2022-01-04',
    category: ['Risoto', 'Lançamentos'],
  },
  {
    id: '8947',
    title: 'Salmão Grelhado com Legumes',
    description:
      'Filé de salmão grelhado acompanhado de legumes frescos cozidos no vapor e molho de limão siciliano.',
    price: 150,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-05',
    updated_at: '2022-01-05',
    category: ['Peixe', 'Lançamentos'],
  },
  {
    id: '8948',
    title: 'Pizza Margherita',
    description:
      'Pizza de massa fina com molho de tomate, muçarela de búfala, tomate fresco e manjericão.',
    price: 35,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-06',
    updated_at: '2022-01-06',
    category: ['Pizza', 'Lançamentos'],
  },
  {
    id: '8949',
    title: 'Lasanha à Bolonhesa',
    description:
      'Camadas de massa de lasanha intercaladas com molho de carne bolonhesa, molho branco e queijo parmesão gratinado.',
    price: 110,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-07',
    updated_at: '2022-01-07',
    category: ['Lasanha', 'Lançamentos'],
  },
  {
    id: '8950',
    title: 'Salada Caesar',
    description:
      'Alface romana fresca, croutons de pão, lascas de parmesão e molho Caesar cremoso.',
    price: 45,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-08',
    updated_at: '2022-01-08',
    category: ['Salada', 'Lançamentos'],
  },
  {
    id: '8951',
    title: 'Sopa de Legumes',
    description:
      'Sopa quente e reconfortante feita com uma variedade de legumes frescos, caldo de galinha e temperos.',
    price: 30,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-09',
    updated_at: '2022-01-09',
    category: ['Sopa', 'Lançamentos'],
  },
  {
    id: '8952',
    title: 'Hambúrguer Clássico',
    description:
      'Hambúrguer suculento de carne bovina grelhada, alface, tomate, queijo cheddar, picles e molho especial, servido com batatas fritas.',
    price: 80,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-10',
    updated_at: '2022-01-10',
    category: ['Hambúrguer', 'Lançamentos'],
  },
  {
    id: '8953',
    title: 'Nhoque à Bolonhesa',
    description:
      'Nhoque de batata caseiro servido com molho de carne bolonhesa e queijo parmesão ralado.',
    price: 95,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-11',
    updated_at: '2022-01-11',
    category: ['Nhoque', 'Lançamentos'],
  },
  {
    id: '8954',
    title: 'Torta de Frango',
    description:
      'Torta caseira recheada com frango desfiado, milho, ervilha, cenoura e temperos, coberta com massa folhada crocante.',
    price: 60,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-12',
    updated_at: '2022-01-12',
    category: ['Torta', 'Lançamentos'],
  },
  {
    id: '8955',
    title: 'Sushi Variado',
    description:
      'Seleção de sushis e sashimis frescos, incluindo salmão, atum, peixe branco e camarão, acompanhados de molho de soja e wasabi.',
    price: 130,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-13',
    updated_at: '2022-01-13',
    category: ['Sushi', 'Lançamentos'],
  },
  {
    id: '8956',
    title: 'Coxinha de Frango',
    description:
      'Deliciosas coxinhas de frango caseiras, recheadas com frango desfiado temperado e fritas até ficarem crocantes.',
    price: 25,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-14',
    updated_at: '2022-01-14',
    category: ['Petiscos', 'Lançamentos'],
  },
  {
    id: '8957',
    title: 'Macarrão ao Molho Pesto',
    description:
      'Macarrão penne servido com molho pesto feito com manjericão fresco, alho, pinhões, queijo parmesão e azeite de oliva.',
    price: 85,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-15',
    updated_at: '2022-01-15',
    category: ['Macarrão', 'Lançamentos'],
  },
  {
    id: '8958',
    title: 'Camarão à Baiana',
    description:
      'Camarões frescos cozidos em um molho de leite de coco, azeite de dendê, pimentões, tomate, cebola e coentro, acompanhado de arroz branco.',
    price: 140,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-16',
    updated_at: '2022-01-16',
    category: ['Frutos do Mar', 'Lançamentos'],
  },
  {
    id: '8959',
    title: 'Picanha Grelhada',
    description:
      'Suculenta picanha grelhada na brasa, servida com farofa, vinagrete, arroz branco e batatas fritas.',
    price: 170,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-17',
    updated_at: '2022-01-17',
    category: ['Carne', 'Lançamentos'],
  },
  {
    id: '8960',
    title: 'Brigadeiro de Colher',
    description:
      'Brigadeiro cremoso de chocolate feito com leite condensado, cacau em pó, manteiga e granulado, servido em copinhos individuais.',
    price: 20,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-18',
    updated_at: '2022-01-18',
    category: ['Sobremesa', 'Lançamentos'],
  },
  {
    id: '8961',
    title: 'Creme de Papaya com Cassis',
    description:
      'Sobremesa refrescante feita com creme de mamão papaya batido com sorvete de creme e licor de cassis, servido com licor de cassis.',
    price: 40,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-19',
    updated_at: '2022-01-19',
    category: ['Sobremesa', 'Lançamentos'],
  },
  {
    id: '8962',
    title: 'Bife à Milanesa',
    description:
      'Bife de carne bovina empanado e frito, servido com arroz, feijão, batata frita e salada.',
    price: 110,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-20',
    updated_at: '2022-01-20',
    category: ['Bife', 'Lançamentos'],
  },
  {
    id: '8963',
    title: 'Feijoada Completa',
    description:
      'Tradicional feijoada brasileira com feijão preto, linguiça, carne seca, costela suína, orelha de porco, pé de porco, acompanhada de arroz, couve, farofa, laranja e torresmo.',
    price: 130,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-21',
    updated_at: '2022-01-21',
    category: ['Feijoada', 'Lançamentos'],
  },
  {
    id: '8964',
    title: 'Pastel de Queijo',
    description:
      'Pastel frito recheado com queijo muçarela derretido e temperado, acompanhado de molho de pimenta.',
    price: 30,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-22',
    updated_at: '2022-01-22',
    category: ['Petiscos', 'Lançamentos'],
  },
  {
    id: '8965',
    title: 'Peixe à Belle Meunière',
    description:
      'Filé de peixe branco grelhado servido com molho à base de manteiga, suco de limão e salsa, acompanhado de batatas sauté e legumes cozidos no vapor.',
    price: 125,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-23',
    updated_at: '2022-01-23',
    category: ['Peixe', 'Lançamentos'],
  },
  {
    id: '8966',
    title: 'Tiramisù',
    description:
      'Sobremesa italiana clássica feita com camadas de biscoitos de champagne embebidos em café, creme de queijo mascarpone e cacau em pó.',
    price: 50,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-24',
    updated_at: '2022-01-24',
    category: ['Sobremesa', 'Lançamentos'],
  },
  {
    id: '8967',
    title: 'Pão de Alho',
    description:
      'Pão francês recheado com pasta de alho e ervas, assado na churrasqueira até dourar, servido quente.',
    price: 20,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-25',
    updated_at: '2022-01-25',
    category: ['Petiscos', 'Lançamentos'],
  },
  {
    id: '8968',
    title: 'Arroz de Pato',
    description:
      'Arroz cozido com pedaços de pato desfiado, linguiça, presunto, chouriço, cenoura e ervilhas.',
    price: 135,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-26',
    updated_at: '2022-01-26',
    category: ['Arroz', 'Lançamentos'],
  },
  {
    id: '8969',
    title: 'Salada Caprese',
    description:
      'Salada fresca e colorida feita com tomate fatiado, queijo muçarela de búfala, manjericão fresco, azeite de oliva extra virgem e redução de balsâmico.',
    price: 40,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-27',
    updated_at: '2022-01-27',
    category: ['Salada', 'Lançamentos'],
  },
  {
    id: '8970',
    title: 'Risoto de Camarão',
    description:
      'Risoto cremoso preparado com camarões frescos, arroz arbóreo, caldo de peixe, vinho branco, cebola, alho, tomate e queijo parmesão.',
    price: 145,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-28',
    updated_at: '2022-01-28',
    category: ['Risoto', 'Lançamentos'],
  },
  {
    id: '8971',
    title: 'Churrasco Misto',
    description:
      'Seleção de carnes grelhadas na brasa, incluindo picanha, fraldinha, linguiça, coração de frango e queijo coalho, acompanhadas de farofa, vinagrete e pão de alho.',
    price: 160,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-29',
    updated_at: '2022-01-29',
    category: ['Churrasco', 'Lançamentos'],
  },
  {
    id: '8972',
    title: 'Mousse de Chocolate',
    description:
      'Sobremesa aerada e deliciosa feita com chocolate amargo derretido, gemas, açúcar, claras em neve e creme de leite batido.',
    price: 35,
    img: 'https://source.unsplash.com/random',
    created_at: '2022-01-30',
    updated_at: '2022-01-30',
    category: ['Sobremesa', 'Lançamentos'],
  },
]

export const dataCategory = [
  'Espaguete',
  'Lançamentos',
  'Filé',
  'Risoto',
  'Peixe',
  'Pizza',
  'Lasanha',
  'Salada',
  'Sopa',
  'Hambúrguer',
  'Nhoque',
  'Torta',
  'Sushi',
  'Petiscos',
  'Macarrão',
  'Frutos do Mar',
  'Carne',
  'Sobremesa',
  'Bife',
  'Feijoada',
  'Arroz',
  'Churrasco',
]
